// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjbnNGQcGllHwGal2NIUPTAstnUlSwaw',
    appId: '1:719842751658:web:6a6741fea6402a70514cd3',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    authDomain: 'safe-driver-system.firebaseapp.com',
    databaseURL: 'https://safe-driver-system-default-rtdb.firebaseio.com',
    storageBucket: 'safe-driver-system.firebasestorage.app',
    measurementId: 'G-EVL44XM90H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcibaYhXUItkAhrUQuugWyDirmQ3-0VfY',
    appId: '1:719842751658:android:988282b039bd42f4514cd3',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    databaseURL: 'https://safe-driver-system-default-rtdb.firebaseio.com',
    storageBucket: 'safe-driver-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoGAHEp-lDg0WuA6H29FzklC0IX0zzxGs',
    appId: '1:719842751658:ios:e1f5fca0fce6e7dd514cd3',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    databaseURL: 'https://safe-driver-system-default-rtdb.firebaseio.com',
    storageBucket: 'safe-driver-system.firebasestorage.app',
    iosClientId: '719842751658-jcu31lfo5s42nrog8ireupk6voosfomc.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeDriverDriverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoGAHEp-lDg0WuA6H29FzklC0IX0zzxGs',
    appId: '1:719842751658:ios:e1f5fca0fce6e7dd514cd3',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    databaseURL: 'https://safe-driver-system-default-rtdb.firebaseio.com',
    storageBucket: 'safe-driver-system.firebasestorage.app',
    iosClientId: '719842751658-jcu31lfo5s42nrog8ireupk6voosfomc.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeDriverDriverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB88lAZy6Dd5KCEhR_g2wZ0MwyvBUtTOgs',
    appId: '1:719842751658:web:ff65eb8362f8dc64514cd3',
    messagingSenderId: '719842751658',
    projectId: 'safe-driver-system',
    authDomain: 'safe-driver-system.firebaseapp.com',
    databaseURL: 'https://safe-driver-system-default-rtdb.firebaseio.com',
    storageBucket: 'safe-driver-system.firebasestorage.app',
    measurementId: 'G-PQZ4XTLYPV',
  );
}
